package org.computer.whunter.javalin

import io.javalin.Context
import io.javalin.Handler
import io.javalin.Javalin
import java.time.Instant
import java.util.*

/**
 * An experiment with Javlin, the lightweight web server. Inspired by the March/April
 * edition of the Java Magazine.
 *
 * @author Warwick Hunter
 * @since 2019-03-12
 */
fun main(args: Array<String>) {

    val controller = HelloController()

    val port = 8000
    println("Starting Javalin on port $port")

    val app = Javalin.create()
        .enableAutogeneratedEtags()
        .start(port)
    app.get("/") { ctx ->
        ctx.result("Hello world\n")
    }
    app.get("/hello", controller)
    app.get("/json")  { ctx -> ctx.json(HelloResult()) }
    app.get("/query") { ctx ->
        val what = ctx.queryParam("q", UUID.randomUUID().toString()) ?: ""
        ctx.json(HelloResult(what))
    }
}

class HelloController: Handler {

    override fun handle(ctx: Context) {
        ctx.result("Hello world2\n")
    }
}

data class HelloResult(val hello:String = "world", val time: Instant = Instant.now())